

export const ERROR_CODE_CAN_NOT_READ_BLOB_BY_FILE_READER = 1;



export const ERROR_CODE_NOT_JPG_FILE_BY_BINARY_CHECKING = 5;
export const ERROR_CODE_NOT_VALID_JPG_MARKER = 51;
export const ERROR_CODE_NOT_VALID_JPG_EXIF_START = 52;
export const ERROR_CODE_NOT_VALID_JPG_EXIF_ENDIAN_VALUE = 53;
export const ERROR_CODE_NOT_VALID_EXIF_TIFF_HEADER_MARK_TAG = 54;
export const ERROR_CODE_NOT_VALID_EXIF_TIFF_HEADER_OFFSET_TO_FIRST_IFD = 55;







